const libs = [
  "Java",
"C#",
"discordcr",
"Nyxx",
"Discord.Net",
"DSharpPlus",
"Nostrum",
"coxir",
"DiscordGo",
"Discord4J",
"Javacord",
"python",
"JDA",
"discord.js",
"Eris",
"Discordia",
"RestCord",
"Yasmin",
"disco",
"discord.py",
"discordrb",
"serenity",
"SwiftDiscord",
"Sword",
"Other",
"Dbd"
  ]

const tags = [
  'moderation',
  'music',
  'customizable',
  'fun',
  'web panel',
  'utility',
  'social',
  'game',
  'roleplay',
  'economy',
  'stream',
  'logging',
  'pubg',
  'multitask',
  'role management'

  ]

const html = "h1"|| "h2" || "`" || "#" || "##"|| "<style>"|| "<iframe>"|| "```";

const reasons_bc = [
		"owner_not_in_server",
		"respond_other_bot",
		"respond_itself",
		"respond_feedback_loop",
		"msg_on_join",
		"msg_random",
		"msg_ads",
		"msg_spam",
		"msg_level_up",
		"no_documentation",
		"no_response",
		"bot_is_clone",
		"bot_is_offline",
		"bot_is_userbot",
		"bot_gained_sentience",
		"bot_token_leaked",
		"bot_no_prefix",
		"bot_code_grant",
		"bot_private",
		"bot_wrong_invite",
		"response_nsfw_outside_nsfw",
		"response_invalid",
		"discord_against_tos",
		"discord_ratelimits",
		"other_tos",
  "bot description have nsfw content",
  ];


const reasons_deny = [
		"owner_not_in_server",
		"respond_other_bot",
		"respond_itself",
		"respond_feedback_loop",
		"msg_on_join",
		"msg_random",
		"msg_ads",
		"msg_spam",
		"msg_level_up",
		"no_documentation",
		"no_response",
		"bot_is_clone",
		"bot_is_offline",
		"bot_is_userbot",
		"bot_gained_sentience",
		"bot_token_leaked",
		"bot_no_prefix",
		"bot_code_grant",
		"bot_private",
		"bot_wrong_invite",
		"response_nsfw_outside_nsfw",
		"response_invalid",
		"discord_against_tos",
		"discord_ratelimits",
		"other_tos",
  "Help command doesn't working",
  "Bot doesn't responding"
  ];

module.exports = {tags,libs,html,reasons_bc,reasons_deny}
